language: node_js
node_js:
  - 12

services:
  - docker

install:
  - echo "Oke agba ni mo gun"

before_script:
  - echo "E ma je ki n jabo"

# TODO: Figure out automatic versioning & tagging
script:
  - docker --version
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy theyorubayesian/reverseproxy:v1
  - docker tag udagram-api-feed theyorubayesian/udagram-api-feed:v1
  - docker tag udagram-api-user theyorubayesian/udagram-api-user:v1
  - docker tag udagram-frontend theyorubayesian/udagram-frontend:v1

after_success:
  - echo "Eyin agba, mo be yin o. Mi o sako"
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push theyorubayesian/reverseproxy:v1
  - docker push theyorubayesian/udagram-api-feed:v1
  - docker push theyorubayesian/udagram-api-user:v1
  - docker push theyorubayesian/udagram-frontend:v1
